# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=1500']
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: name-tests-test
        args: ['--pytest-test-first']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.9
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    - id: nbstripout
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: python3 -m pytest -x -m "not slow"
      pass_filenames: false
      language: system
      types: [python]
