# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    - id: nbqa-black
    - id: nbqa-isort
      args: ["--float-to-top"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
    - id: nbstripout
  - repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: python3 -m pytest -vx -m "not slow"
      pass_filenames: false
      language: system
      types: [python]
